### ISSUE TITLE
Goblin Stats

### ISSUE THREAD

**Issue by jensdietrich** [nkiru-ede/MavenNetworkStudy#23]
@nkiru-ede  we have edge and vertex counts in different charts atm (GA vertices, GA edges, GAV vertices, GAV edges). Could we please combine them into a single chart with 4 lines ? Log scale as before. We wont have sufficient space for four charts, and this is not our core message, we merely need this to show the rate of growth. 

Also, please add this in a new figures/ top level folder. We should only have charts we use in the paper in this folder, this will make things easier if we have to upload paper sources later.

**Comment by jensdietrich** [comment]
@nkiru-ede  thanks, chart looks good - please QA those values. In particular: in Figure~\ref{fig:counts} the GA edges counts are smaller than the GA vertex counts. This is not intuitive, and needs an explanation. For the old dataset I have observed an vertex / edge ratio of 0.2 !!

But do some general cross-checks on the data, what I see are only the "known unknows" - there are also "unknown unkn owns".  

cc @ulizue

**Comment by nkiru-ede** [comment]
@jensdietrich yes, this is not very different in the new dataset.. the average vertex/edge ratio in the new dataset for gav is 0.1262

I will update the GA chart.
