### ISSUE TITLE
additional columns for GA and G graphs

### ISSUE THREAD

**Issue by jensdietrich** [nkiru-ede/MavenNetworkStudy#3]
1. add column `Source_First_Version_Release_Date` to G and GA
2. add column `Source_First_Version_Release_Year` to G and GA
3. add column `Taget_First_Version_Release_Date` to G and GA
4. add column `Target_First_Version_Release_Year` to G and GA
5. add column `Source_Version_Count` to G and GA
6. add column `Target_Version_Count` to G and GA

This implies that we need different schemas for GAV, GA and G. 

For G, also: 

1. add column `Source_Artifact_Count` to G 
2. add column `Target_Artifact_Count` to G

**Comment by nkiru-ede** [comment]
This is done and schema files are converted to TSV. 
@jensdietrich please confirm

**Comment by jensdietrich** [comment]
@nkiru-ede  please double check the following:

1. make file extensions consistently lower case, on some OSs this matters
2. check capitalisation of columns (e.g. in [Schema_G.TSV](https://github.com/nkiru-ede/MavenNetworkStudy/blob/main/data/Schema_G.TSV) this is inconsistent
3. there are still columns missing -- look for symmetry between source and target columns 
4. if we have `Source_First_Version_Release_Year` should we also have `Source_Last_Version_Release_Year` ? (same for target)

**Comment by nkiru-ede** [comment]
@jensdietrich 
1. done
2. done
3. and 4. done

**Comment by jensdietrich** [comment]
@nkiru-ede   is Schema_GA.tsv what is the difference between  `Source_Release_Date` and `Source_Last_Release_Date` / `Source_First_Release_Date` ?  This is not clear from the description (check other schemas / columns as well). Please start asking yourself those questions before committing.

**Comment by nkiru-ede** [comment]
done @jensdietrich

**Comment by jensdietrich** [comment]
@nkiru-ede in todays meeting please explain rationale behind 
`Source_Release_Date`  (*The release date of the source artifact before aggregation*) column in the schema for G (and similar columns in G,GA)


`

**Comment by jensdietrich** [comment]
@nkiru-ede as just discussed please remove redundant columns
