### ISSUE TITLE
remove redundant scripts

### ISSUE THREAD

**Issue by jensdietrich** [nkiru-ede/MavenNetworkStudy#6]
[aggregate.py](https://github.com/nkiru-ede/MavenNetworkStudy/blob/main/unitTest/aggregate.py) and https://github.com/nkiru-ede/MavenNetworkStudy/blob/main/Project/dataanalysis.py are redundant. Remove [aggregate.py](https://github.com/nkiru-ede/MavenNetworkStudy/blob/main/unitTest/aggregate.py), tests should reference the main script.

**Comment by nkiru-ede** [comment]
@jensdietrich done

**Comment by jensdietrich** [comment]
confirmed
