### ISSUE TITLE
clean up raw data

### ISSUE THREAD

**Issue by jensdietrich** [nkiru-ede/MavenNetworkStudy#8]
Looking at the raw data [data/GAV1.zip](data/GAV1.zip) there are recording like this: 

```
com.actionbarsherlock	actionbarsherlock	4.2.0	2012-10-08T00:40:10Z[GMT]	2012	com.fedepaolapps.postman	sample	1.0.3	2013-04-14T21:34:37Z[GMT]	2013
```

Note that the target release date is after the source release date. However, the semantics of these records is (upstream) dependencies. I.e. source depends on target. The respective data must be checked and tested. 

1. add test script `test_raw_data.py` to test dates
2. manually sample some records from each subdataset and check against primary data -- i.e. whether we can see the dependencies in the Maven repo 

Document 2 in a table in tests (markdown or tsv) with columns as follows: 

`subdataset  | row number | Maven Link`

For instance, for the (fixed, i.e. target and source swapped) example above an entry would look like this:

`data/GAV1 | 10 | [https://mvnrepository.com/artifact/com.fedepaolapps.postman/sample/1.0.3](https://mvnrepository.com/artifact/com.fedepaolapps.postman/sample/1.0.3)`

**Comment by nkiru-ede** [comment]
**### Note that the target release date is after the source release date.**

Please with the above statement, are you referring to the current state of the data? or stating what it should be?

Right thing: **### The source release date should be after the target release date.** Please clarify.

**Comment by jensdietrich** [comment]
@nkiru-ede  source depends on target (i.e. dependency graph edges go into the direction of *depends-on*, from downstream to upstream). Therefore the target artifact must already exist when the source artifact with the dependency is published, and therefore the source release date must be after the target release date. In the record above this was not the case, so the input data (GAV*.tsv) must be changed and tested.

Btw, you could use property-based testing here, look at [https://semaphoreci.com/blog/property-based-testing-python-hypothesis-pytest](https://semaphoreci.com/blog/property-based-testing-python-hypothesis-pytest).

**Comment by nkiru-ede** [comment]
noted. Thank you @jensdietrich

**Comment by nkiru-ede** [comment]
for 2. please see manually checked sample data in [data/SampleCheck](https://github.com/nkiru-ede/MavenNetworkStudy/blob/main/data/SampleCheck.txt)

**Comment by jensdietrich** [comment]
@nkiru-ede   -- this starts looking like real tests now -- well done ! Two notes / questions:   I would relocate the test data from `data` into `tests` -- perhaps check for python conventions where test data should be. For instance, in Maven tests are is `src/test/java` and test data in `src/test/resources` -- I assume that pythin does something similar here.

You use the function `pd.testing.assert_frame_equal(processed_df, expected_df)` to compare the output of script like `process_merged_G` with the oracle `expected_data `. But the oracle has only a single row, but the script produced 3 rows. How does this work ? Perhaps extend the oracle to test all three rows. Can you assume that the order of rows produced by the script is deterministic ? If not tests may become [flaky](https://www.jetbrains.com/teamcity/ci-cd-guide/concepts/flaky-tests).

**Comment by nkiru-ede** [comment]
@jensdietrich there are 5 rows in the test data and 3 rows are expected after the aggregation. I am a bit confused with what you mean in the second part of your comment.

**Comment by jensdietrich** [comment]
@nkiru-ede Looking at https://github.com/nkiru-ede/MavenNetworkStudy/blob/main/tests/test_aggregate_g.py :
`expected_data` is a single record (line 23)
`processed_df` contains three rows (lines 40 and 46)
so in line 47 the assertion contains 1 row with 3 rows and seems to return true -- how does this work ?  Is this just comparing the top row in `processed_df` ?

**Comment by jensdietrich** [comment]
@nkiru-ede  we discussed this last time -- `expected_data` is a 2d structure, issue can be closed.
