### ISSUE TITLE
insert processing step to transform raw data from zenodo into input format used by aggregation 

### ISSUE THREAD

**Issue by jensdietrich** [nkiru-ede/MavenNetworkStudy#9]
Zenodo data (from [https://zenodo.org/records/1489120/files/maven-data.csv.tar.xz?download=1](https://zenodo.org/records/1489120/files/maven-data.csv.tar.xz?download=1) from [Benelallam et al paper](https://ieeexplore.ieee.org/iel7/8804710/8816727/08816814.pdf) uses a different format with dependencies and release timestamps in different tables, it also uses CVS not TSV. Some scripts are needed to transform this into the single TSV-based table representation we use. This needs to be documented as a separate step ("prepare"), tested, described in readme etc.

**Comment by nkiru-ede** [comment]
done @jensdietrich
